import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import jsPDF from "jspdf";
import "./ViewCV.css";

function ViewCV() {
  const { id } = useParams();
  const [cv, setCv] = useState(null);
  const [template, setTemplate] = useState("classic");

  useEffect(() => {
    fetch(`http://localhost:60/api/cv/single/${id}`)
      .then(res => res.json())
      .then(data => setCv(data))
      .catch(err => console.error("Error fetching CV:", err));
  }, [id]);

  if (!cv) return <p>Loading...</p>;

  // ================= CLASSIC =================
  const classicTemplate = (doc) => {
    let y = 20;

    doc.setFontSize(20);
    doc.text(cv.name || "", 10, y);
    y += 10;

    doc.setFontSize(12);
    doc.text(`Email: ${cv.email || ""}`, 10, y); y += 8;
    doc.text(`Phone: ${cv.phone || ""}`, 10, y); y += 8;
    doc.text(`Address: ${cv.address || ""}`, 10, y); y += 8;
    doc.text(`Age: ${cv.age || ""}`, 10, y); y += 8;
    doc.text(`Gender: ${cv.gender || ""}`, 10, y); y += 12;

    doc.text("Experience:", 10, y); y += 6;
    const exp = doc.splitTextToSize(cv.experience || "", 180);
    doc.text(exp, 10, y);
    y += exp.length * 6 + 5;

    doc.text("Skills:", 10, y); y += 6;
    const skills = doc.splitTextToSize(cv.skills || "", 180);
    doc.text(skills, 10, y);
    y += skills.length * 6 + 5;

    doc.text("Habits:", 10, y); y += 6;
    const habits = doc.splitTextToSize(cv.habits || "", 180);
    doc.text(habits, 10, y);
  };

  // ================= MODERN =================
  const modernTemplate = (doc) => {
    // Sidebar
    doc.setFillColor(33, 150, 243);
    doc.rect(0, 0, 60, 297, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(16);
    doc.text(cv.name || "", 10, 20);

    doc.setFontSize(10);
    const contact = doc.splitTextToSize(
      `${cv.email}\n${cv.phone}\n${cv.address}\nAge: ${cv.age}\nGender: ${cv.gender}`,
      45
    );
    doc.text(contact, 10, 40);

    // Right side
    let y = 20;
    doc.setTextColor(0, 0, 0);

    doc.setFontSize(14);
    doc.text("Experience", 70, y);
    y += 8;
    const exp = doc.splitTextToSize(cv.experience || "", 120);
    doc.text(exp, 70, y);
    y += exp.length * 6 + 10;

    doc.text("Education", 70, y);
    y += 8;
    const edu = doc.splitTextToSize(cv.education || "", 120);
    doc.text(edu, 70, y);
    y += edu.length * 6 + 10;

    doc.text("Skills", 70, y);
    y += 8;
    const skills = doc.splitTextToSize(cv.skills || "", 120);
    doc.text(skills, 70, y);
    y += skills.length * 6 + 10;

    doc.text("Habits", 70, y);
    y += 8;
    const habits = doc.splitTextToSize(cv.habits || "", 120);
    doc.text(habits, 70, y);
  };

  const minimalTemplate = (doc) => {
    let y = 20;

    const brown = [92, 64, 51];
    const lightBrown = [180, 150, 130];

    doc.setFont("helvetica", "bold");
    doc.setFontSize(24);
    doc.setTextColor(...brown);
    doc.text(cv.name || "", 105, y, { align: "center" });

    y += 10;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);

    const header = doc.splitTextToSize(
      `${cv.email} | ${cv.phone} | ${cv.address} | Age: ${cv.age} | Gender: ${cv.gender}`,
      170
    );
    doc.text(header, 105, y, { align: "center" });
    y += header.length * 6 + 5;

    doc.setDrawColor(...lightBrown);
    doc.line(20, y, 190, y);
    y += 10;

    // Experience
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(...brown);
    doc.text("EXPERIENCE", 20, y);
    y += 8;

    doc.setFont("helvetica", "normal");
    doc.setTextColor(0, 0, 0);
    const exp = doc.splitTextToSize(cv.experience || "", 160);
    doc.text(exp, 25, y);
    y += exp.length * 6 + 10;

    doc.line(20, y, 190, y);
    y += 10;

    doc.setFont("helvetica", "bold");
    doc.setTextColor(...brown);
    doc.text("SKILLS", 20, y);
    y += 8;

    doc.setFont("helvetica", "normal");
    const skills = doc.splitTextToSize(cv.skills || "", 160);
    doc.text(skills, 25, y);
    y += skills.length * 6 + 10;

    doc.line(20, y, 190, y);
    y += 10;

    // Habits
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...brown);
    doc.text("HABITS", 20, y);
    y += 8;

    doc.setFont("helvetica", "normal");
    const habits = doc.splitTextToSize(cv.habits || "", 160);
    doc.text(habits, 25, y);

    doc.setFontSize(9);
    doc.setTextColor(...lightBrown);
    doc.text("Generated by Resume Builder", 105, 285, { align: "center" });
  };
const executiveTemplate = (doc) => {
  doc.setFillColor(30, 30, 30);
  doc.rect(0, 0, 210, 35, "F");

  doc.setTextColor(255, 215, 0);
  doc.setFontSize(24);
  doc.text(cv.name || "", 15, 22);

  doc.setTextColor(0, 0, 0);

  let y = 50;

  doc.setFontSize(12);
  doc.text(`Email: ${cv.email}`, 15, y);
  y += 8;

  doc.text(`Phone: ${cv.phone}`, 15, y);
  y += 8;

  doc.text(`Address: ${cv.address}`, 15, y);
  y += 15;

  doc.setFontSize(16);
  doc.text("Experience", 15, y);
  y += 10;

  const exp = doc.splitTextToSize(cv.experience || "", 170);
  doc.text(exp, 15, y);

  y += exp.length * 6 + 10;

  doc.text("Skills", 15, y);
  y += 10;

  const skills = doc.splitTextToSize(cv.skills || "", 170);
  doc.text(skills, 15, y);

  y += skills.length * 6 + 10;

  doc.text("Habits", 15, y);
  y += 10;

  const habits = doc.splitTextToSize(cv.habits || "", 170);
  doc.text(habits, 15, y);
};
const brownTemplate = (doc) => {
  doc.setFillColor(92, 64, 51);
  doc.rect(0, 0, 55, 297, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.text(cv.name || "", 8, 20);

  doc.setFontSize(10);
  doc.text(cv.email || "", 8, 40);
  doc.text(cv.phone || "", 8, 50);
  doc.text(cv.address || "", 8, 60);

  doc.setTextColor(0, 0, 0);

  let y = 25;

  doc.setFontSize(15);
  doc.text("Experience", 70, y);

  y += 10;

  const exp = doc.splitTextToSize(cv.experience || "", 120);
  doc.text(exp, 70, y);

  y += exp.length * 6 + 10;

  doc.text("Education", 70, y);

  y += 10;

  const edu = doc.splitTextToSize(cv.education || "", 120);
  doc.text(edu, 70, y);

  y += edu.length * 6 + 10;

  doc.text("Skills", 70, y);

  y += 10;

  const skills = doc.splitTextToSize(cv.skills || "", 120);
  doc.text(skills, 70, y);

  y += skills.length * 6 + 10;

  doc.text("Habits", 70, y);

  y += 10;

  const habits = doc.splitTextToSize(cv.habits || "", 120);
  doc.text(habits, 70, y);
};
const corporateTemplate = (doc) => {
  let y = 20;

  doc.setFillColor(0, 82, 204);
  doc.rect(0, 0, 210, 25, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.text(cv.name || "", 15, 17);

  y = 40;

  doc.setTextColor(0, 0, 0);

  doc.text(`Email: ${cv.email}`, 15, y);
  y += 8;

  doc.text(`Phone: ${cv.phone}`, 15, y);
  y += 8;

  doc.text(`Address: ${cv.address}`, 15, y);
  y += 15;

  doc.setDrawColor(0, 82, 204);
  doc.line(15, y, 195, y);

  y += 10;

  doc.setFontSize(15);
  doc.text("Experience", 15, y);

  y += 10;

  const exp = doc.splitTextToSize(cv.experience || "", 170);
  doc.text(exp, 15, y);

  y += exp.length * 6 + 10;

  doc.text("Skills", 15, y);

  y += 10;

  const skills = doc.splitTextToSize(cv.skills || "", 170);
  doc.text(skills, 15, y);

  y += skills.length * 6 + 10;

  doc.text("Habits", 15, y);

  y += 10;

  const habits = doc.splitTextToSize(cv.habits || "", 170);
  doc.text(habits, 15, y);
};
  // ================= DOWNLOAD =================
  const downloadPDF = () => {
    const doc = new jsPDF();

    if (template === "classic") classicTemplate(doc);
else if (template === "modern") modernTemplate(doc);
else if (template === "minimal") minimalTemplate(doc);
else if (template === "executive") executiveTemplate(doc);
else if (template === "brown") brownTemplate(doc);
else if (template === "corporate") corporateTemplate(doc);

    doc.save(`${cv.name || "CV"}_CV.pdf`);
  };
return (  <>
    <div className="cv-container">
<div className="maincv11">
      <select onChange={(e) => setTemplate(e.target.value)}>
        <option value="classic">Classic</option>
        <option value="modern">Modern</option>
        <option value="minimal">Minimal</option>
        <option value="executive">Executive</option>
<option value="brown">Brown Sidebar</option>
<option value="corporate">Corporate Blue</option>
      </select>

       <div className="cv-header">
    <h1>{cv.name}</h1>
    <p>{cv.email}</p>
    <p>{cv.phone}</p>
    <p>{cv.address}</p>
    <p>Age: {cv.age}</p>
    <p>Gender: {cv.gender}</p>
  </div>

  <div className="cv-body">

    <div className="left">
      <div className="cv-section">
        <h2>Experience</h2>
        <p>{cv.experience}</p>
      </div>

      <div className="cv-section">
        <h2>Education</h2>
        <p>{cv.education}</p>
      </div>
    </div>

    <div className="right">
      <div className="cv-section">
        <h2>Skills</h2>
        <p>{cv.skills}</p>
      </div>

      <div className="cv-section">
        <h2>Habits</h2>
        <p>{cv.habits}</p>
      </div>
    </div>

  </div>
  <button className="download-btn" onClick={downloadPDF}>
    Download PDF
  </button>
</div>


</div>
  </>
  );
}

export default ViewCV;